// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"
	"time"
)

type Address struct {
	ID           int32  `json:"id"`
	UnitNumber   string `json:"unit_number"`
	AddressLine1 string `json:"address_line1"`
	AddressLine2 string `json:"address_line2"`
	PostalCode   int32  `json:"postal_code"`
}

type CustomerAddress struct {
	ID        int32         `json:"id"`
	UserID    sql.NullInt32 `json:"user_id"`
	AddressID sql.NullInt32 `json:"address_id"`
}

type UserCookie struct {
	ID        int32     `json:"id"`
	UserName  string    `json:"user_name"`
	CookieID  int32     `json:"cookie_id"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type UserDetail struct {
	ID           int32     `json:"id"`
	FirstName    string    `json:"first_name"`
	LastName     string    `json:"last_name"`
	UserName     string    `json:"user_name"`
	UserPassword string    `json:"user_password"`
	Email        string    `json:"email"`
	Mobile       int32     `json:"mobile"`
	CreatedAt    time.Time `json:"created_at"`
}
