// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"
)

type Address struct {
	ID           int32  `json:"id"`
	UnitNumber   string `json:"unit_number"`
	AddressLine1 string `json:"address_line1"`
	AddressLine2 string `json:"address_line2"`
	PostalCode   int32  `json:"postal_code"`
}

type CustomerAddress struct {
	ID        int32         `json:"id"`
	UserID    sql.NullInt32 `json:"user_id"`
	AddressID sql.NullInt32 `json:"address_id"`
}

type UserDetail struct {
	ID        int32  `json:"id"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	UserName  string `json:"user_name"`
	Email     string `json:"email"`
	Mobile    int32  `json:"mobile"`
}
