// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: user.sql

package db

import (
	"context"
	"time"
)

const createAddress = `-- name: CreateAddress :one
INSERT INTO address (
unit_number,
address_line1,
address_line2,
postal_code
) VALUES(
    $1, $2, $3, $4
) RETURNING id, unit_number, address_line1, address_line2, postal_code
`

type CreateAddressParams struct {
	UnitNumber   string `json:"unit_number"`
	AddressLine1 string `json:"address_line1"`
	AddressLine2 string `json:"address_line2"`
	PostalCode   int32  `json:"postal_code"`
}

func (q *Queries) CreateAddress(ctx context.Context, arg CreateAddressParams) (Address, error) {
	row := q.db.QueryRowContext(ctx, createAddress,
		arg.UnitNumber,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.PostalCode,
	)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.UnitNumber,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.PostalCode,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO user_details (
first_name,
last_name,
user_name,
user_password,
email,
mobile
) VALUES(
    $1, $2, $3, $4, $5, $6
) RETURNING id, first_name, last_name, user_name, user_password, email, mobile, created_at
`

type CreateUserParams struct {
	FirstName    string `json:"first_name"`
	LastName     string `json:"last_name"`
	UserName     string `json:"user_name"`
	UserPassword string `json:"user_password"`
	Email        string `json:"email"`
	Mobile       int32  `json:"mobile"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (UserDetail, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.FirstName,
		arg.LastName,
		arg.UserName,
		arg.UserPassword,
		arg.Email,
		arg.Mobile,
	)
	var i UserDetail
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.UserName,
		&i.UserPassword,
		&i.Email,
		&i.Mobile,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCookieByID = `-- name: DeleteCookieByID :one
DELETE FROM user_cookies WHERE id = $1 RETURNING id
`

func (q *Queries) DeleteCookieByID(ctx context.Context, id int32) (int32, error) {
	row := q.db.QueryRowContext(ctx, deleteCookieByID, id)
	err := row.Scan(&id)
	return id, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, first_name, last_name, user_name, user_password, email, mobile, created_at FROM user_details WHERE user_name = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, userName string) (UserDetail, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, userName)
	var i UserDetail
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.UserName,
		&i.UserPassword,
		&i.Email,
		&i.Mobile,
		&i.CreatedAt,
	)
	return i, err
}

const insertCookie = `-- name: InsertCookie :one
INSERT INTO user_cookies (user_name ,cookie_id, expires_at) VALUES ($1, $2, $3) RETURNING id, user_name, cookie_id, expires_at, created_at
`

type InsertCookieParams struct {
	UserName  string    `json:"user_name"`
	CookieID  int32     `json:"cookie_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) InsertCookie(ctx context.Context, arg InsertCookieParams) (UserCookie, error) {
	row := q.db.QueryRowContext(ctx, insertCookie, arg.UserName, arg.CookieID, arg.ExpiresAt)
	var i UserCookie
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.CookieID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const selectCookieByID = `-- name: SelectCookieByID :one
SELECT id, user_name, cookie_id, expires_at, created_at FROM user_cookies WHERE id = $1 AND expires_at > NOW() LIMIT 1
`

func (q *Queries) SelectCookieByID(ctx context.Context, id int32) (UserCookie, error) {
	row := q.db.QueryRowContext(ctx, selectCookieByID, id)
	var i UserCookie
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.CookieID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
